# Generated by Django 4.2.6 on 2023-10-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0005_comment_created_at_comment_user_project_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectmembership',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMembership',
        ),
    ]
