# Generated by Django 4.2.6 on 2023-10-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_projectmembership_project_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyLog',
        ),
    ]
