# Generated by Django 4.2.6 on 2023-10-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_delete_dailylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sprint',
        ),
    ]
